apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-configmap
  namespace: git
data:
  MYSQL_USER: zabbix
  MYSQL_DATABASE: zabbix
  DB_SERVER_HOST: zabbix-mariadb-service
  # DB_SERVER_HOST: zabbix-db-service
  DB_SERVER_PORT: "3306"
  ZBX_SERVER_HOST: zabbix-server-service
  ZBX_SERVER_PORT: "10051"
  ZBX_HOSTNAME: "Zabbix server"
  ZBX_SERVER_NAME: "Zabbix GIT Digital"
  ZBX_AGENT_SERVER_HOST: 127.0.0.1
  ZBX_STARTPINGERS: "10"
